server:
  port: 8080

inference:
  model-dir: /models
  thread-count: ${INFERENCE_THREAD_COUNT:4}
  model-sources: ${MODEL_SOURCES:http://58.220.240.50:17007/public-test/sample-model.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20260509%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260509T124301Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&versionId=73fad5b0-bbbe-4136-9c76-3cc2d0fa11a2&X-Amz-Signature=9a4ffd3300eda3e605624104c2f6a5e76d135995de37fa38aa09200e101123eb}
  s3:
    enabled: ${S3_ENABLED:false}
    endpoint: ${S3_ENDPOINT:}
    region: ${S3_REGION:us-east-1}
    bucket: ${S3_BUCKET:}
    access-key: ${S3_ACCESS_KEY:}
    secret-key: ${S3_SECRET_KEY:}
    path-style-access: ${S3_PATH_STYLE_ACCESS:false}

host-proc:
  base-path: ${HOST_PROC_PATH:/host/proc}

management:
  endpoints:
    web:
      exposure:
        include: health,info
