FROM harbor.tianyishuju.com/skyease/onnx-java-inference-base:latest

COPY model.onnx /models/sample-custom-step/model.onnx
COPY model.yml /models/sample-custom-step/model.yml
COPY custom-step-*.jar /models/sample-custom-step/steps/
