FROM harbor.tianyishuju.com/skyease/onnx-java-inference-base:latest

COPY model.onnx /models/sample-model/model.onnx
COPY model.yml /models/sample-model/model.yml
COPY target/onnx-java-inference-sample-operators-*.jar /models/sample-model/operators/
